# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: José Ribamar  Alvino JR
author-title: Full Stack Developer
#gravatar: d36a082aacb53b6f76869748fb4b81d4
email: ribamar.alvino@gmail.com
#twitter: 
#github: 
googleplus: +ribamar.alvino
facebook: ribamar.alvino
linkedin: josé-r-alvino-31156b21
bio: "Brazilian Architect & Developer. Food, music, arts and technology lover.
      I'm a Bachelor Degree in Business Administration. 
	  I'm a Microsoft Application Developer Certified (MCAD), IBM Certified Specialist (IMB-CP) - Software Quality, Motorola RFID Solutions Certified.
	  ISO 27001 Certified, Certified Security Officer (MCSO), Developer Security Software Specialist, MSDN Brazil Five Stars Developer
	  I love to study and learn new skills, exchange work and study experience with people around me and share my knowledge with the ones that want it. I work with Web Development since 1993 and with
      Mobile Development since 2014 as Freelancer and in some Brazilian companies too.
      For now, woring for big and small companies in Brazil developing great enterpprise projects with modern UI frameworks and infratructure solutions. 
      I like to work with both: Front-End and Back-End development. I work with many languages, frameworks and technologies."
      I always worked with developer and IT (Servers, Ethernet, LAN, WAN, Switches, Database, Storage NAS, SAS), Virtulization, Security, Criptography, TCP/IP ."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 4
  - name: CSS 3
    level: 4
  - name: JavaScript
    level: 4
  - name: jQuery
    level: 4
  - name: Angular
    level: 3
  - name: Bootstrap
    level: 4

back-end:
   - Web API 2
    level: 4
  - Asp.net MVC 5
    level: 4
	 - LINQ
    level: 4
  - name: C#
    level: 5
  - name: Node.js
    level: 3
  - name: C++
    level: 3
  - name: C
    level: 3
  - name: Delphi
    level: 4
  - name: VB6
    level: 4
  - name: VB.Net
    level: 3
  - name: SQL
    level: 4
  - name: Transact SQL
    level: 4
  - name: PL/SQL
    level: 4
  - name: WCF
    level: 4
  - Sharepoint 2010
    level: 4
  - Sharepoint 2013
    level: 4
  - name: MS Project Server
    level: 4
 

mobile:
  - name: Android (MS Visual Studio 2015)
    level: 2
  - name: Apache Cordova (MS Visual Studio 2015)
    level: 2
  - name: Xamarin (MS Visual Studio 2015)
    level: 2
	- name: Arduino
    level: 4
  - name: GPS
    level: 4
	- name: GPRS/GSM
    level: 3
db:
 - name: SQL Azure 
    level: 4 
- name: MySQL
    level: 4
  - name: PostgreSQL
    level: 4
  - name: MongoDB
    level: 4
  - name: SQL Server
    level: 4
  - name: Oracle
    level: 4
  - name: Firebird
    level: 3
  - name: NoSQL
    level: 3
- name: Couch Base
    level: 3
- name: SQLite
    level: 4

Infrastructure:
  - name: Amazon Web Services
    level: 4
	  - name: Windows Azure
    level: 4
  - name: Windows Servers
    level: 5
  - name: Linux
    level: 3
  - name: Hyper-V
    level: 3
  - name: VMWare ESX
    level: 4
  - name: VirtualBox
    level: 5
	- name: TCP/IP
    level: 5
	- name: Active Directory/DNS/DHCP/SMTP/IMAP/POP
    level: 5
	- name: Digital Certificates (PKI)
    level: 4
	- name: IIS
    level: 5
	

devops:
  - name: TFS
    level: 4
  - name: Git
    level: 3
  - name: Continuous Integration
    level: 2
  - name: Continuous Delivery
    level: 2

methodologies:
  - name: Agile Methodologies
    level: 3
  - name: Scrum
    level: 3
  - name: RUP
    level: 4

others:
  - name: Web Services SOAP
    level: 5
  - name: REST
    level: 5
  - name: Entity Framework
    level: 4
  - name: Visual Studio
    level: 4
  - name: NHibernate
    level: 3
  - name: MVC
    level: 4
  - UML
    level: 4
  - BPM
    level: 4 
  - GED/ECM
    level: 5
	  - RFID
    level: 4  

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap, bourbon]
